image: artifactory.wma.chs.usgs.gov/docker-official-mirror/rocker/tidyverse:latest

default:
  tags:
    - chs-shared
    - dind

stages:
  - getready
  - check
  - test
  - end

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_SUGGESTS_ONLY: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  _R_CHECK_DONTTEST_EXAMPLES_: "false"
  R_PROFILE: "$R_HOME/etc/Rprofile.site"
  APT_CACHE: "$CI_PROJECT_DIR/ci/lib/apt-cache"
  CRAN: "https://rpkg.chs.usgs.gov/prod-cran/latest"
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  R_LIBS: "$CI_PROJECT_DIR/ci/lib"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs"
  NOT_CRAN: "true"
  CONNECT_API_KEY: $CONNECT_API_KEY
  CONNECT_SERVER: $CONNECT_SERVER

cache:
  paths:
    - $R_LIBS_USER


getready:
  stage: getready
  script:
    - mkdir -p $R_LIBS_USER
    - mkdir -p $APT_CACHE
    - echo "options(Ncpus=$(nproc --all), repos=c(CRAN='$CRAN'))" >> $R_PROFILE
    - Rscript -e "install.packages(c('devtools', 'pkgdown', 'covr', 'connectapi'))"
    - Rscript -e 'remotes::install_deps(dependencies=TRUE)'
  cache:
    paths:
     - $R_LIBS_USER
  artifacts:
    paths:
     - $R_LIBS_USER

buildcheck:
  stage: check
  script:
    - mkdir -p $BUILD_LOGS_DIR
    - apt-get update
    - apt-get -o dir::cache::archives=${APT_CACHE} install -y --no-install-recommends qpdf pandoc pandoc-citeproc
    - R CMD build . --no-manual
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", check_dir = Sys.getenv("BUILD_LOGS_DIR"))'
  artifacts:
    paths:
      - $BUILD_LOGS_DIR

unittests:
  stage: test
  dependencies:
    - getready
    - buildcheck
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

covertests:
  stage: test
  dependencies:
    - getready
    - buildcheck
  script:
    - R -e 'covr::package_coverage()'
  coverage: '/Coverage: \d+.\d+\%/'

deploy:
  stage: end
  only: 
    - main
  script:
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'source("deploy_simple.R")'
  artifacts:
    paths:
      - $PKG_PATH
    expire_in: 1 week